// ============================================================
// ✈️ VINES DE GUERRA — Aviones Militares Modernos
// ============================================================

const warVines = [
  // ─── CAZAS 5TA GENERACIÓN ───
  {
    id: 1,
    title: "F-22 Raptor: El Depredador Invisible",
    type: "Caza de Superioridad Aérea",
    country: "🇺🇸 EE.UU.",
    year: "2005",
    generation: "5ta Gen",
    image: "🦅",
    color: "#7f8c8d",
    short: "El caza más letal jamás construido. Y ya no se fabrica.",
    full: "El F-22 Raptor es el primer caza de 5ta generación en entrar en servicio. Combina stealth, supercrucero (vuelo supersónico sin postquemador), y aviónica fusionada. Puede detectar y destruir un objetivo antes de que el enemigo sepa que está ahí. Solo se fabricaron 187 unidades — el Congreso detuvo la producción por costos ($350M c/u). Está prohibida su exportación.",
    stat: "Velocidad máxima: Mach 2.25 | Techo: 20 km | Radar: AN/APG-77 AESA",
    impact: "Definió el estándar de 5ta generación que todos intentan copiar."
  },
  {
    id: 2,
    title: "F-35 Lightning II: El Caza Polémico",
    type: "Caza Multirrol Stealth",
    country: "🇺🇸 EE.UU. (+ socios)",
    year: "2015",
    generation: "5ta Gen",
    image: "⚡",
    color: "#f39c12",
    short: "El programa militar más caro de la historia: $1.7 billones.",
    full: "El F-35 es un caza multirrol con tres variantes (F-35A convencional, F-35B despegue vertical, F-35C naval). Su sensor de fusión DAS permite al piloto 'ver a través' del avión. Ha sido criticado por sobrecostos, bugs de software y problemas en pruebas. Pero cuando funciona, es una máquina de guerra conectada que comparte datos en tiempo real con toda la flota.",
    stat: "Costo del programa: $1.7T | 3,000+ pedidos | 15 países lo operan",
    impact: "Columna vertebral de la aviación militar de la OTAN por décadas."
  },
  {
    id: 3,
    title: "Su-57 Felon: La Respuesta Rusa",
    type: "Caza Stealth Multirrol",
    country: "🇷🇺 Rusia",
    year: "2020",
    generation: "5ta Gen",
    image: "🇷🇺",
    color: "#c0392b",
    short: "Rusia dice que es stealth. Occidente no está tan seguro.",
    full: "El Su-57 Felon es el primer caza stealth de Rusia. Tiene motores con vectorización de empuje 3D que le dan una maniobrabilidad increíble. Pero ha tenido una producción limitada (menos de 25 unidades), y las sanciones han afectado su desarrollo. Se ha usado en combate real en Ucrania lanzando misiles desde territorio ruso, evitando zonas con defensas aéreas densas.",
    stat: "Velocidad: Mach 2.0 | Radar: Byelka AESA | Producción: ~20 unidades",
    impact: "Rusia demostró que puede hacer stealth, pero no producirlo en masa."
  },
  {
    id: 4,
    title: "J-20 Chengdu: El Poder Asiático",
    type: "Caza Stealth de Superioridad",
    country: "🇨🇳 China",
    year: "2017",
    generation: "5ta Gen",
    image: "🐉",
    color: "#e74c3c",
    short: "China tiene su propio caza stealth. Y viene con misiles larguísimos.",
    full: "El J-20 Mighty Dragon es el primer caza stealth operacional de China. Tiene un diseño tipo canard-delta, bahías de armas internas, y misiles PL-15 con alcance de 300 km — superando a cualquier misil aire-aire occidental. Se estima que China ya tiene más de 200 unidades operativas, superando la flota de F-22. Su motor WS-15 local es el talón de Aquiles en desarrollo.",
    stat: "Alcance: 5,500 km | Misil PL-15: 300 km de alcance | 200+ unidades",
    impact: "China alcanzó paridad tecnológica en aviación de combate mucho antes de lo esperado."
  },

  // ─── CAZAS 4TA GEN / 4.5 ───
  {
    id: 5,
    title: "F-16 Fighting Falcon: El Multipropósito",
    type: "Caza Multirrol",
    country: "🇺🇸 EE.UU.",
    year: "1978",
    generation: "4ta Gen",
    image: "🔱",
    color: "#3498db",
    short: "El caza más producido de Occidente: 4,600+ unidades.",
    full: "El F-16 es el caballo de batalla de la aviación occidental. Diseñado como caza ligero diurno, evolucionó a multirrol completo. Su asiento reclinado a 30° y su burbuja de cabina sin marco le dan visibilidad total. Ha servido en 25+ países. A pesar de ser de los 70s, sigue en producción con actualizaciones que lo mantienen relevante. Es el caza más letal de India, Israel, Turquía y muchos más.",
    stat: "4,600+ fabricados | 25+ países | 2,000+ derribos en combate simulados",
    impact: "El diseño más exitoso de caza ligero en la historia de la aviación."
  },
  {
    id: 6,
    title: "Su-35 Flanker-E: El Rey de la Agilidad",
    type: "Caza Pesado Multirrol",
    country: "🇷🇺 Rusia",
    year: "2014",
    generation: "4.5 Gen",
    image: "🦅",
    color: "#d4ac0d",
    short: "El caza 4.5 más maniobrable del mundo.",
    full: "El Su-35 es la evolución máxima del diseño Su-27 Flanker. Sus motores AL-41F1S con vectorización de empuje 3D le permiten hacer maniobras imposibles para cualquier otro caza: cobra de Pugachev, giros de 360° sin perder energía. Tiene radar Irbis-E con alcance de 400 km. Se ha enfrentado a sistemas de defensa aérea ucranianos con resultados mixtos — potente pero no invisible.",
    stat: "12 puntos de anclaje | 8 toneladas de carga bélica | Radar 400 km",
    impact: "Probablemente el mejor caza 4.5 jamás construido — solo superado por stealth."
  },
  {
    id: 7,
    title: "F-15EX Eagle II: El Veterano Renacido",
    type: "Caza de Superioridad Aérea",
    country: "🇺🇸 EE.UU.",
    year: "2021",
    generation: "4.5 Gen",
    image: "🛡️",
    color: "#2c3e50",
    short: "El F-15 de los 70s, pero con cerebro del F-35.",
    full: "El F-15EX es la versión más avanzada del diseño clásico F-15. Lleva el radar AN/APG-82 AESA, computadoras de misión del F-35, y guerra electrónica digital. Puede cargar 12 misiles aire-aire AMRAAM — el doble que un F-35. Se llama '4.5 gen' porque no es stealth, pero su radar y sensores son 5ta gen. La USAF lo compró como complemento barato para el F-35.",
    stat: "12 misiles AMRAAM | Velocidad: Mach 2.5 | Carga: 13 toneladas",
    impact: "Probó que los diseños viejos con electrónica moderna siguen siendo mortales."
  },

  // ─── BOMBARDEROS ───
  {
    id: 8,
    title: "B-2 Spirit: El Fantasma Volador",
    type: "Bombardero Stealth",
    country: "🇺🇸 EE.UU.",
    year: "1997",
    generation: "Stealth",
    image: "👻",
    color: "#566573",
    short: "El avión más caro de la historia por unidad: $2.1B.",
    full: "El B-2 Spirit es un bombardero furtivo con forma de ala volante. Su diseño lo hace invisible al radar — aparece como un pájaro en las pantallas. Puede penetrar las defensas aéreas más densas del mundo y lanzar bombas guiadas JDAM con precisión milimétrica. Solo se construyeron 21. Necesita hangares climatizados especiales que cuestan millones. Su mantenimiento es tan caro que vuela menos de lo planeado.",
    stat: "$2.1B por unidad | 21 construidos | Autonomía: 11,000 km sin reabastecer",
    impact: "Demostró que la guerra invisible era posible. El B-21 lo reemplazará."
  },
  {
    id: 9,
    title: "B-52 Stratofortress: El Inmortal",
    type: "Bombardero Estratégico",
    country: "🇺🇸 EE.UU.",
    year: "1955",
    generation: "Leyenda",
    image: "⏳",
    color: "#7d3c98",
    short: "El abuelo de la flota. Volará hasta los 100 años.",
    full: "El B-52 entró en servicio en 1955 y la USAF planea mantenerlo hasta 2050+. Ha sobrevivido a todos sus reemplazos propuestos. Sus 8 motores turbofan le dan una presencia icónica. Ha lanzado de todo: bombas convencionales, nucleares, misiles de crucero. En Vietnam, su 'Arc Light' era el sonido del infierno. En Afganistán e Irak, daba apoyo con bombas guiadas. Es el avión militar de larga distancia más longevo de la historia.",
    stat: "En servicio desde 1955 | Hasta 2050+ | 70 toneladas de carga máxima",
    impact: "Ningún otro bombardero ha servido tanto tiempo ni en tantas guerras."
  },
  {
    id: 10,
    title: "B-21 Raider: El Futuro del Bombardeo",
    type: "Bombardero Stealth de 6ta Gen",
    country: "🇺🇸 EE.UU.",
    year: "2022 (revelado)",
    generation: "6ta Gen",
    image: "🔮",
    color: "#1a5276",
    short: "El bombardero más avanzado de la historia. Casi nada se sabe de él.",
    full: "El B-21 Raider es el nuevo bombardero stealth de Northrop Grumman. Se reveló en diciembre de 2022. Diseñado para ser modular, con capacidad tripulada/no tripulada, y conectar con drones acompañantes (CCA). Usa inteligencia artificial para planificar rutas de penetración. Costará ~$700M por unidad, significativamente menos que el B-2. Se esperan 100+ unidades.",
    stat: "100+ planificados | $700M c/u | Tecnología de 6ta generación",
    impact: "Definirá la capacidad de bombardeo estratégico de EE.UU. por 50 años."
  },

  // ─── AVIONES DE ATAQUE ───
  {
    id: 11,
    title: "A-10 Warthog: La Bestia de Tanques",
    type: "Avión de Ataque a Tierra",
    country: "🇺🇸 EE.UU.",
    year: "1977",
    generation: "A-10",
    image: "🐗",
    color: "#5d6d7e",
    short: "Un avión construido alrededor de un cañón de 30mm.",
    full: "El A-10 Thunderbolt II, apodado Warthog, es un avión de apoyo cercano diseñado para matar tanques. Su cañón GAU-8/A Avenger de 30mm dispara proyectiles de uranio empobrecido — literalmente puede partir un tanque por la mitad. Está blindado como un tanque volador: una cabina de titanio de 540 kg protege al piloto de fuego antiaéreo. Puede volar con un ala, un motor y medio timón perdidos. Ha sobrevivido a 4 intentos de retiro.",
    stat: "GAU-8: 3,900 balas/minuto | 1,300 kg de blindaje | 30 años de servicio",
    impact: "El A-10 ha salvado más tropas terrestres que cualquier otro avión."
  },
  {
    id: 12,
    title: "Su-25 Frogfoot: El Warthog Ruso",
    type: "Avión de Ataque a Tierra",
    country: "🇷🇺 Rusia",
    year: "1981",
    generation: "Ataque",
    image: "🐸",
    color: "#717d7e",
    short: "La contraparte soviética del A-10. Menos preciso, más duro.",
    full: "El Su-25 Frogfoot es el avión de apoyo cercano soviético/ruso. Menos sofisticado que el A-10, pero extremadamente robusto. Su cabina está blindada con titanio y puede seguir volando con daños masivos. Se ha usado extensamente en Afganistán, Chechenia, Siria y Ucrania. En Ucrania ha sufrido pérdidas significativas por MANPADS y misiles antiaéreos — la guerra moderna no perdona a los aviones de vuelo bajo.",
    stat: "1,000+ fabricados | 30+ países | Sigue en producción",
    impact: "Probó que el apoyo cercano es vital incluso en guerras modernas."
  },

  // ─── AVIONES NAVALES ───
  {
    id: 13,
    title: "F/A-18 Super Hornet: El Rey del Mar",
    type: "Caza Multirrol Embarcado",
    country: "🇺🇸 EE.UU.",
    year: "1999",
    generation: "4.5 Gen",
    image: "⚓",
    color: "#2980b9",
    short: "El caza naval más versátil de la historia.",
    full: "El F/A-18 Super Hornet es la espina dorsal de la aviación naval de EE.UU. Es 25% más grande y mucho más avanzado que el Hornet original. Puede despegar y aterrizar en portaaviones, hacer reabastecimiento en vuelo, combate aire-aire, ataque a tierra, y guerra electrónica (crecer growler). Su radar APG-79 AESA y su capacidad de llevar 11,000 kg de armas lo hacen excepcionalmente versátil.",
    stat: "11,000 kg de carga | 1,500 km de alcance | Mach 1.8",
    impact: "Columna vertebral de la aviación embarcada de EE.UU. hasta el F-35C."
  },
  {
    id: 14,
    title: "MiG-29K: El Caza del Mar Ruso",
    type: "Caza Embarcado",
    country: "🇷🇺 Rusia",
    year: "2013",
    generation: "4.5 Gen",
    image: "🌊",
    color: "#bdc3c7",
    short: "Opera desde el único portaaviones de Rusia, el Almirante Kuznetsov.",
    full: "El MiG-29K es la versión naval del Fulcrum, diseñado para operar desde portaaviones. Tiene alas plegables, gancho de detención, y tren de aterrizaje reforzado para cubiertas. Rusia los opera desde el Kuznetsov, un portaaviones problemático que siempre echa humo. La India también los usa desde el INS Vikramaditya. Les falta tecnología stealth y modernización AESA.",
    stat: "Alcance: 2,000 km | Carga: 5,500 kg | Producción: ~50 unidades navales",
    impact: "Rusia mantiene capacidad de aviación naval, aunque limitada."
  },

  // ─── HELICÓPTEROS ───
  {
    id: 15,
    title: "AH-64 Apache: La Pesadilla Blindada",
    type: "Helicóptero de Ataque",
    country: "🇺🇸 EE.UU.",
    year: "1986",
    generation: "Ataque",
    image: "🐍",
    color: "#2c3e50",
    short: "El helicóptero de ataque más letal del planeta.",
    full: "El AH-64 Apache es el helicóptero de ataque principal del Ejército de EE.UU. y 16 países más. Su radar de control de fuego Longbow puede detectar 256 objetivos, priorizar 16 y atacar simultáneamente. Sus misiles Hellfire perforan cualquier blindaje conocido. Por la noche, su sistema FLIR y visión nocturna le dan superioridad total. Sigue mejorando con el modelo AH-64E Guardian.",
    stat: "16 misiles Hellfire | 76 cohetes Hydra | 1,200+ fabricados",
    impact: "Definió el helicóptero de ataque moderno. Nadie lo ha superado."
  },
  {
    id: 16,
    title: "Ka-52 Alligator: El Tanque Volador Ruso",
    type: "Helicóptero de Ataque",
    country: "🇷🇺 Rusia",
    year: "2011",
    generation: "Ataque",
    image: "🐊",
    color: "#e67e22",
    short: "Helicóptero con asientos eyectables (único en el mundo).",
    full: "El Ka-52 Alligator es único: tiene rotores coaxiales contrarrotatorios (sin rotor de cola), lo que le da una maniobrabilidad excepcional. Y sí, tiene asientos eyectables — los únicos en un helicóptero de producción. Antes de eyectarse, las palas del rotor se separan con cargas explosivas. En Ucrania ha sido efectivo pero ha sufrido numerosas pérdidas por MANPADS y defensas aéreas.",
    stat: "Velocidad: 310 km/h | 12 misiles Vikhr antitanque | Asientos eyectables",
    impact: "Innovación técnica rusa que nadie más ha replicado."
  },
  {
    id: 17,
    title: "CH-47 Chinook: El Camión Volador",
    type: "Helicóptero de Transporte Pesado",
    country: "🇺🇸 EE.UU.",
    year: "1962",
    generation: "Transporte",
    image: "🚁",
    color: "#aab7b8",
    short: "El helicóptero bimotor con rotores tándem más famoso.",
    full: "El CH-47 Chinook es un helicóptero de transporte pesado con dos rotores tándem. Puede levantar 12 toneladas de carga o 55 soldados completamente equipados. Ha servido en todas las guerras de EE.UU. desde Vietnam. Su diseño le permite operar en condiciones extremas: desiertos, montañas, selvas. Es tan icónico que su 'wop-wop-wop' se reconoce instantáneamente.",
    stat: "12 toneladas de carga | 55 soldados | 1,200+ fabricados | 60+ años de servicio",
    impact: "El helicóptero de batalla más fiable jamás construido."
  },

  // ─── EUROPEOS ───
  {
    id: 18,
    title: "Eurofighter Typhoon: El Hit Europeo",
    type: "Caza Multirrol",
    country: "🇪🇺 Europa (UK, Alemania, Italia, España)",
    year: "2003",
    generation: "4.5 Gen",
    image: "🌍",
    color: "#2e86c1",
    short: "El caza europeo que vuela a Mach 2 sin postquemador.",
    full: "El Eurofighter Typhoon es un caza de diseño canard-delta excepcionalmente ágil. Sus motores EJ200 le permiten supercrucero — volar supersónico sin postquemador, ahorrando combustible. Tiene radar Captor-E AESA y puede llevar misiles Meteor (el mejor misil BVR del mundo). En ejercicios de la OTAN, regularmente 'derriba' F-22 en combate cerrado. Es el orgullo de la aviación europea.",
    stat: "Velocidad: Mach 2.0 | 680+ fabricados | 9 países operadores",
    impact: "Europa demostró que puede competir con EE.UU. en diseño de cazas."
  },
  {
    id: 19,
    title: "Dassault Rafale: El Todoterreno Francés",
    type: "Caza Omirrol",
    country: "🇫🇷 Francia",
    year: "2004",
    generation: "4.5 Gen",
    image: "🥖",
    color: "#21618c",
    short: "Francia lo hizo solo. Y es letal en todo: aire, tierra, mar.",
    full: "El Rafale es un caza 'omirrol' francés — puede hacer cualquier misión: combate aéreo, ataque nuclear, bombardeo de precisión, reconocimiento y operaciones navales desde portaaviones. Francia lo desarrolló independientemente, rechazando el Eurofighter. Tiene un 80% de contenido francés. Ha demostrado su valía en Afganistán, Libia, Mali, Siria e Irak. También lo compran India, Egipto, Catar y Grecia.",
    stat: "Mach 1.8 | 14 puntos de anclaje | 9.5 toneladas de carga",
    impact: "Un caza hecho 100% por un solo país europeo. Soberanía tecnológica."
  },
  {
    id: 20,
    title: "JAS 39 Gripen: El Caza Minimalista",
    type: "Caza Multirrol Ligero",
    country: "🇸🇪 Suecia",
    year: "1997",
    generation: "4.5 Gen",
    image: "🦁",
    color: "#f1c40f",
    short: "Puede operar desde carreteras. Sí, carreteras.",
    full: "El Saab Gripen fue diseñado para la defensa de Suecia durante la Guerra Fría: necesita pistas cortas, mantenimiento mínimo (10 horas-hombre por hora de vuelo, vs 40+ del F-16), y puede reabastecerse y rearmarse en 10 minutos con solo 5 técnicos. Puede aterrizar en carreteras. Su radar ES-05 Raven AESA y misiles Meteor lo hacen letal a bajo costo operativo.",
    stat: "Costo por hora de vuelo: ~$4,700 | Operación desde carreteras | 10 min de rearme",
    impact: "El caza más eficiente del mundo. Mucho avión por poco dinero."
  },

  // ─── DRONES ───
  {
    id: 21,
    title: "MQ-9 Reaper: El Ángel de la Muerte",
    type: "Vehículo Aéreo No Tripulado (UCAV)",
    country: "🇺🇸 EE.UU.",
    year: "2007",
    generation: "Drone de Ataque",
    image: "💀",
    color: "#424949",
    short: "Pilotado desde una pantalla a 12,000 km de distancia.",
    full: "El MQ-9 Reaper es el drone de ataque más famoso del mundo. Pilotado desde Nevada mientras vuela sobre Afganistán o Yemen. Puede llevar 4 misiles Hellfire y 2 bombas GBU-12 Paveway II, sobrevolar 27 horas seguidas, y transmitir video en alta definición las 24 horas. Fue clave en la Guerra contra el Terror. Su uso plantea serias preguntas éticas: ¿es legal matar por control remoto?",
    stat: "27 horas de autonomía | 4 Hellfire + 2 bombas | Costo: $16M",
    impact: "Cambió la naturaleza de la guerra. Ahora matar es como jugar un videojuego."
  },
  {
    id: 22,
    title: "Bayraktar TB2: El Drone del Pueblo",
    type: "UCAV Táctico",
    country: "🇹🇷 Turquía",
    year: "2014",
    generation: "Drone Táctico",
    image: "🪁",
    color: "#e74c3c",
    short: "Un drone barato que cambió guerras. Y se volvió meme.",
    full: "El Bayraktar TB2 es un drone turco de bajo costo ($5M) que se ha convertido en un símbolo de guerra moderna. Destruyó sistemas antiaéreos rusos en Nagorno-Karabaj y Ucrania. Es lento, no stealth, pero su cámara de alta definición y sus municiones guiadas MAM lo hacen devastador contra blindados desprotegidos. Su éxito inspiró una canción, memes y hasta aparece en sellos postales de Ucrania.",
    stat: "Autonomía: 27 horas | Techo: 25,000 pies | Costo: $5M | 30+ países",
    impact: "Demostró que un drone barato puede destruir tanques que cuestan 100x más."
  },

  // ─── ESPECIALES ───
  {
    id: 23,
    title: "SR-71 Blackbird: El Cohete con Alas",
    type: "Avión de Reconocimiento Estratégico",
    country: "🇺🇸 EE.UU.",
    year: "1966",
    generation: "Leyenda",
    image: "🚀",
    color: "#17202a",
    short: "Mach 3.2 a 26 km de altura. Ningún misil pudo alcanzarlo jamás.",
    full: "El SR-71 Blackbird es el avión tripulado más rápido y alto de la historia. Volaba a Mach 3.2 (3,540 km/h) a 26 km de altura. Su fuselaje de titanio se expansionaba 15 cm en vuelo por el calor. No podía tener depósitos de combustible herméticos — perdía combustible en tierra y solo sellaba al alcanzar velocidad. Podía fotografiar 260,000 km² en una hora. Nunca fue derribado — ni por misiles ni por interceptores.",
    stat: "Mach 3.2 | 26 km de altura | 3,540 km/h | 0 derribos en 34 años",
    impact: "El pináculo de la aviación de reconocimiento. No hay nada igual desde su retiro."
  },
  {
    id: 24,
    title: "F-117 Nighthawk: El Abuelo Stealth",
    type: "Caza Furtivo de Ataque",
    country: "🇺🇸 EE.UU.",
    year: "1983",
    generation: "Stealth Pionero",
    image: "🌙",
    color: "#5d6d7e",
    short: "El avión que nunca debió existir. Hasta que lo vieron.",
    full: "El F-117 Nighthawk fue el primer avión operacional diseñado con tecnología stealth. Su forma angular y facetada no era aerodinámicamente eficiente — volaba como un ladrillo. Pero era invisible al radar. Se usó en Panamá, y en 1991 en la Guerra del Golfo, donde 30 F-117 lanzaron el 40% de las bombas guiadas con láser con precisión letal. Fue retirado en 2008 pero EE.UU. lo mantuvo en secreto hasta 1988.",
    stat: "59 construidos | Primer stealth operacional | 0 pérdidas en combate (Golfo)",
    impact: "Demostró que la invisibilidad al radar era real y letal."
  },
  {
    id: 25,
    title: "E-3 Sentry AWACS: El Ojo Volador",
    type: "Alerta Temprana y Control",
    country: "🇺🇸 EE.UU.",
    year: "1977",
    generation: "AWACS",
    image: "👁️",
    color: "#1abc9c",
    short: "Un radar volador que ve todo en 400 km a la redonda.",
    full: "El E-3 Sentry es un Boeing 707 modificado con un radar rotatorio de 9 metros de diámetro. Puede detectar aviones enemigos a 400 km, dirigir cazas amistosos, y coordinar todo el espacio aéreo de una batalla. En la Guerra del Golfo, los AWACS dirigieron 35,000 salidas aéreas y coordinaron 88,000 misiones. Es la pieza central de cualquier operación aérea moderna.",
    stat: "Radar: 400 km de alcance | 17 tripulantes | 30+ días de operación continua",
    impact: "El centro de control volador. Sin AWACS, la guerra aérea moderna es imposible."
  },
  {
    id: 26,
    title: "V-22 Osprey: El Híbrido Polémico",
    type: "Convertiplano (Tiltrotor)",
    country: "🇺🇸 EE.UU.",
    year: "2007",
    generation: "Tiltrotor",
    image: "🔄",
    color: "#f39c12",
    short: "Despega como helicóptero, vuela como avión. Y tuvo un historial accidentado.",
    full: "El V-22 Osprey es un tiltrotor: despega verticalmente como helicóptero pero gira sus motores hacia adelante para volar como avión turbohélice. Vuela el doble de rápido y tres veces más lejos que un helicóptero convencional. Su desarrollo fue problemático — 30 muertos en accidentes de prueba. Hoy es fundamental para operaciones especiales de la USMC y USSOCOM, con mejoras continuas de seguridad.",
    stat: "Velocidad: 510 km/h | Alcance: 1,600 km | 24 tropas o 7 toneladas",
    impact: "Probó que el tiltrotor es viable. Sin él no existiría el V-280 Valor."
  },

  // ─── MÁS CAZAS ───
  {
    id: 27,
    title: "MiG-31 Foxhound: El Interceptor Supersónico",
    type: "Interceptor de Alta Velocidad",
    country: "🇷🇺 Rusia",
    year: "1981",
    generation: "Interceptor",
    image: "⚡",
    color: "#aab7b8",
    short: "Mach 2.83 y misiles que alcanzan satélites.",
    full: "El MiG-31 Foxhound es un interceptor puro, diseñado para cazar bombardeos estratégicos y misiles de crucero a velocidades extremas. Puede volar a Mach 2.83 y disparar el misil R-37M con alcance de 400 km — el misil aire-aire de mayor alcance del mundo. También puede lanzar un misil anti-satélite. Ucrania ha perdido varios aviones por estos misiles lanzados desde territorio ruso.",
    stat: "Mach 2.83 | Misil R-37M: 400 km | Radar Zaslon: 300 km",
    impact: "El único caza diseñado específicamente para misiles hipersónicos y ASAT."
  },
  {
    id: 28,
    title: "F-14 Tomcat: El Icono de los 80s",
    type: "Interceptor Embarcado",
    country: "🇺🇸 EE.UU.",
    year: "1974",
    generation: "4ta Gen",
    image: "🐱",
    color: "#e67e22",
    short: "Top Gun lo hizo famoso. El misil Phoenix lo hizo temible.",
    full: "El F-14 Tomcat es el caza embarcado más icónico de la historia gracias a la película Top Gun. Sus alas de geometría variable se abrían para vuelo lento y se cerraban para supersónico. Podía disparar el misil AIM-54 Phoenix, que derribaba blancos a 200 km — el misil aire-aire más letal de su época. Irán aún opera F-14 comprados antes de la revolución de 1979, aunque con dificultades.",
    stat: "Mach 2.34 | 6 misiles Phoenix simultáneos | Alas variables",
    impact: "El caza más carismático de la historia. Símbolo del poder aéreo estadounidense."
  },
  {
    id: 29,
    title: "Su-34 Fullback: El Bombardero Cazador",
    type: "Caza Bombardero Táctico",
    country: "🇷🇺 Rusia",
    year: "2014",
    generation: "4.5 Gen",
    image: "🦆",
    color: "#515a5a",
    short: "Un caza con baño y cocina. No es broma.",
    full: "El Su-34 Fullback es un caza bombardero de largo alcance con una característica absurda: tiene un mini baño y una cocina para misiones largas. Su cabina es biplaza lado a lado (no en tándem), y la tripulación puede turnarse para dormir en el pasillo entre los asientos. En Ucrania ha sido muy usado para bombardeos tácticos, pero ha sufrido pérdidas significativas por defensas aéreas.",
    stat: "Alcance: 4,500 km | Carga: 12 toneladas | Tripulación: 2 (lado a lado)",
    impact: "El avión de ataque táctico de largo alcance más potente de Rusia."
  },
  {
    id: 30,
    title: "KAI FA-50: El Caza Coreano",
    type: "Caza Ligero / Entrenador Avanzado",
    country: "🇰🇷 Corea del Sur",
    year: "2013",
    generation: "4ta Gen Ligero",
    image: "🇰🇷",
    color: "#5dade2",
    short: "Entrenador por fuera, caza letal por dentro.",
    full: "El FA-50 es un entrenador avanzado con capacidad de combate ligero. Corea del Sur lo diseñó para reemplazar entrenadores viejos, pero puede llevar misiles aire-aire, cohetes y bombas guiadas de precisión. Es barato (~$30M), confiable y fácil de mantener. Polonia compró 48 unidades para reemplazar sus MiG-29. Filipinas los usa en combate contra insurgentes. Es el caza de entrada perfecto para países con presupuesto limitado.",
    stat: "Mach 1.5 | Costo: $30M | 7 puntos de anclaje",
    impact: "Demostró que un entrenador puede ser un caza letal si se diseña bien."
  },

  // ─── MÁS DRONES ───
  {
    id: 31,
    title: "MQ-1 Predator: El Pionero de los Drones",
    type: "UAV de Reconocimiento/Ataque",
    country: "🇺🇸 EE.UU.",
    year: "1995",
    generation: "Drone Pionero",
    image: "🦅",
    color: "#808b96",
    short: "El primer drone armado que cambió la guerra para siempre.",
    full: "El MQ-1 Predator fue el primer UAV armado en servicio de EE.UU. Originalmente solo de reconocimiento, en 2001 fue armado con misiles Hellfire. Sobrevoló Afganistán, Irak, Pakistán y Yemen, eliminando objetivos de Al-Qaeda y talibanes. Su cámara y enlace satelital permitían a pilotos en Nevada ver en vivo el campo de batalla. Fue retirado en 2018, reemplazado por el Reaper.",
    stat: "Autonomía: 24 horas | 2 misiles Hellfire | 1,000+ en servicio",
    impact: "Transformó la guerra de contrainsurgencia. El 'asesinato selectivo' nació aquí."
  },
  {
    id: 32,
    title: "DJI Mavic: El Drone de Todos",
    type: "Drone Comercial Militarizado",
    country: "🇨🇳 China",
    year: "2016",
    generation: "Drone Civil de Guerra",
    image: "📱",
    color: "#b03a2e",
    short: "Un drone de $2,000 que se volvió arma de guerra.",
    full: "El DJI Mavic es un drone comercial que cuesta menos que un iPhone. En la guerra de Ucrania, ambos bandos los han adaptado para dejar caer granadas directamente en trincheras enemigas. Los soldados los llaman 'dioses de la guerra': un Mavic modificado puede destruir un tanque de $5M con una granada de $50. La guerra con drones FPV ha cambiado el campo de batalla para siempre.",
    stat: "Costo: ~$2,000 | Autonomía: 30 min | Usado por ejércitos regulares e insurgentes",
    impact: "Cualquiera con $2,000 puede tener un drone de guerra. La guerra se democratizó."
  },

  // ─── PROTOTIPOS Y FUTURO ───
  {
    id: 33,
    title: "NGAD: El Caza Secreto de 6ta Gen",
    type: "Caza de 6ta Generación",
    country: "🇺🇸 EE.UU.",
    year: "?? (clasificado)",
    generation: "6ta Gen",
    image: "❓",
    color: "#1a1a1a",
    short: "El F-22 tiene un hijo. Y nadie sabe cómo es.",
    full: "El Next Generation Air Dominance (NGAD) es el programa secreto de EE.UU. para reemplazar al F-22. Se sabe poco: será un 'sistema de sistemas', combinando un caza tripulado con drones acompañantes (CCA) que actúan como alas leales. Usará inteligencia artificial, motores adaptativos, y posiblemente armas de energía dirigida. Ya hay un prototipo volando desde 2020. Costará cientos de millones por unidad.",
    stat: "Prototipo volando desde 2020 | Presupuesto: $9B+ | IA integrada en el centro",
    impact: "Definirá la guerra aérea de 2050. Si sabemos cómo es, ya es muy tarde."
  },
  {
    id: 34,
    title: "GCAP: El Caza Europeo del Futuro",
    type: "Caza de 6ta Generación",
    country: "🇪🇺 UK, Italia, Japón",
    year: "2035 (estimado)",
    generation: "6ta Gen",
    image: "🌍",
    color: "#1c2833",
    short: "El primer caza 6ta gen con un país asiático como socio.",
    full: "El Global Combat Air Programme (GCAP) une a Reino Unido, Italia y Japón para desarrollar un caza de 6ta generación. Japón aporta tecnología de misiles y electrónica; UK, motores y diseño; Italia, sistemas de integración. Será tripulado con opción no tripulada, con drones acompañantes, y capacidad de controlar enjambres de UAVs. Competirá directamente con el NGAD y el FCAS europeo.",
    stat: "Entrada en servicio: ~2035 | Socios: UK, Italia, Japón | Presupuesto: $40B+",
    impact: "Japón se une por primera vez a un programa de cazas fuera de EE.UU."
  },
  {
    id: 35,
    title: "S-70 Okhotnik-B: El Dron Asesino Ruso",
    type: "Drone de Combate Pesado Stealth",
    country: "🇷🇺 Rusia",
    year: "2019 (prototipo)",
    generation: "UCAV Stealth",
    image: "🦈",
    color: "#566573",
    short: "Un drone del tamaño de un caza. Vuela con el Su-57.",
    full: "El S-70 Okhotnik (Cazador) es un drone de combate pesado de 20 toneladas con diseño de ala volante stealth. Vuela como 'ala leal' del Su-57, recibiendo órdenes y compartiendo datos. Puede llevar misiles, bombas y posiblemente realizar reconocimiento armado. Rusia dice que tiene capacidades de IA para vuelo autónomo. Uno se estrelló en 2019 durante pruebas — normal en desarrollo.",
    stat: "Peso: 20 toneladas | Ala volante stealth | IA integrada",
    impact: "Rusia entra al club de los drones de combate pesados con China y EE.UU."
  },

  // ─── MÁS HELICÓPTEROS ───
  {
    id: 36,
    title: "Mi-28 Havoc: El Cazatanques Nocturno",
    type: "Helicóptero de Ataque",
    country: "🇷🇺 Rusia",
    year: "1996",
    generation: "Ataque",
    image: "👺",
    color: "#717d7e",
    short: "El Apache ruso. Tan letal, tan ruinoso.",
    full: "El Mi-28 Havoc es el helicóptero de ataque pesado de Rusia. Su cañón automático de 30mm, misiles antitanque Ataka, y la capacidad de operar de noche lo hacen un oponente temible. Está fuertemente blindado: la cabina soporta impactos de 12.7mm y 20mm. En Ucrania ha sido usado extensamente pero con pérdidas significativas, lo que ha llevado a Rusia a replantear su doctrina de helicópteros de ataque.",
    stat: "Cañón 2A42 de 30mm | 16 misiles Ataka | Blindaje pesado",
    impact: "Demostró que los helicópteros de ataque son vulnerables en guerras con defensas aéreas densas."
  },

  // ─── AVIONES DE TRANSPORTE ───
  {
    id: 37,
    title: "C-5M Super Galaxy: El Gigante Americano",
    type: "Avión de Transporte Estratégico",
    country: "🇺🇸 EE.UU.",
    year: "1970",
    generation: "Transporte Pesado",
    image: "🐘",
    color: "#2c3e50",
    short: "El avión más grande de la USAF. Carga 2 tanques Abrams.",
    full: "El C-5 Super Galaxy es el monstruo del transporte militar. Puede cargar dos tanques M1 Abrams, 6 helicópteros Apache, o 270 soldados completamente equipados. Tiene 12 alas de combustible, 28 ruedas, y necesita 2.7 km de pista para despegar a máxima carga. Sus 4 motores General Electric TF39 producen 195,000 libras de empuje combinado. Fue modernizado al modelo C-5M con nuevos motores y aviónica.",
    stat: "Carga máxima: 127 toneladas | Envergadura: 68 m | 2 tanques Abrams de carga",
    impact: "La logística militar estratégica de EE.UU. no existiría sin el C-5."
  },
  {
    id: 38,
    title: "An-225 Mriya: El Gigante Perdido",
    type: "Avión de Transporte Superpesado",
    country: "🇺🇦 Ucrania",
    year: "1988",
    generation: "Transporte Récord",
    image: "🦢",
    color: "#1a5276",
    short: "El avión más grande del mundo. Destruido en 2022.",
    full: "El Antonov An-225 Mriya ('Sueño') era el avión más grande y pesado jamás construido. Tenía 6 motores, 32 ruedas y una envergadura de 88 metros. Podía cargar 250 toneladas — incluido el transbordador espacial Burán. Fue destruido en febrero de 2022 durante la invasión rusa de Ucrania en el aeropuerto de Hostomel, donde estaba en reparación. Ucrania planea reconstruirlo como símbolo nacional.",
    stat: "Carga máxima: 250 toneladas | 6 motores | 88 m de envergadura | Único en el mundo",
    impact: "Un símbolo del ingenio ucraniano. Su destrucción fue una pérdida para la aviación mundial."
  },

  // ─── MÁS RECONOCIMIENTO ───
  {
    id: 39,
    title: "RQ-4 Global Hawk: El Satélite Volador",
    type: "UAV de Reconocimiento Estratégico",
    country: "🇺🇸 EE.UU.",
    year: "2001",
    generation: "HALE UAV",
    image: "🛰️",
    color: "#aeb6bf",
    short: "Vuela a 20 km de altura durante 34 horas sin parar.",
    full: "El RQ-4 Global Hawk es un UAV de reconocimiento de gran altitud y larga autonomía (HALE). Puede volar a 20 km de altura durante 34 horas, cubriendo 100,000 km² por misión. Su radar SAR y sensores electro-ópticos pueden ver detalles de 30 cm desde el borde del espacio. Operado desde bases en EE.UU., Alemania, Japón y Guam, ha sobrevolado zonas de conflicto como Siria, Afganistán y el Mar de China Meridional.",
    stat: "34 horas de autonomía | 20 km de altura | Radar: 30 cm de resolución",
    impact: "La capacidad de vigilancia global 24/7 sin poner pilotos en riesgo."
  },
  {
    id: 40,
    title: "U-2 Dragon Lady: El Espía de 60 Años",
    type: "Avión de Reconocimiento de Gran Altitud",
    country: "🇺🇸 EE.UU.",
    year: "1956",
    generation: "Reconocimiento",
    image: "👁️",
    color: "#34495e",
    short: "Sigue volando. A los 70 años. Y sigue siendo clasificado.",
    full: "El U-2 Dragon Lady entró en servicio en 1956 para espiar a la Unión Soviética. Vuela a 21 km de altura — tan alto que los pilotos usan trajes presurizados de astronauta. Los primeros vuelos sobre la URSS capturaron fotos de misiles nucleares soviéticos en Cuba. Increíblemente, sigue en servicio tras 70 años, modernizado con sensores digitales. Es uno de los aviones más longevos y secretos de la historia.",
    stat: "21 km de altura | 70+ años de servicio | Traje de astronauta requerido",
    impact: "El avión espía más exitoso de la historia. Nunca será completamente desclasificado."
  }
];
